env_config:
  env_name: "HalfCheetah-v2"
  max_episode_length: 1000
model_config:
  hidden_layers:
    - 64
    - 64
optimizer_config:
  learning_rate: 0.005
  beta1: 0.9
  beta2: 0.999
  batch_size: 500
max_iteration: 751
num_workers: 14
num_rollouts: 10
num_evaluation: 10
noise_table_size: 250000
noise_table_seed: 1234
noise_sample_seed: 10
delta_std: 0.1
result_path: '/home/xukang/GitRepo/ES/NaturalES/results/'
save_model_interval: 250

estimator_type: 'finite_difference'
fitness_type: 'value'