env_config:
  env_name: "Ant-v2"
  max_episode_length: 500
model_config:
  hidden_layers: 
    - 100
    - 100
optimizer_config:
  learning_rate: 0.001
  beta1: 0.9
  beta2: 0.999
  batch_size: 500
max_iteration: 5000
num_workers: 4
num_rollouts: 10
num_evaluation: 10
noise_table_size: 250000
noise_table_seed: 1234
noise_sample_seed: 10
delta_std: 0.2
result_path: '/home/xukang/GitRepo/ES_base/results/'
save_model_interval: 500